version: '3.7'

services:
  web:
    image: parth812/my-app:latest
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/static/images
    expose:
    - 8000
    env_file:
      - .env

  db:
      image: postgres:15
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=admin

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - .:/app
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/static/images
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
